# Use in your KlipperScreen by adding:
# [include 3ms/KlipperScreenCutter.conf]
# to the KlipperScreen.conf in your printer.cfg folder

[menu __main 3ms cutter]
name: Cutter
icon: filament

[menu __main 3ms cutter cut]
name: Cut Filament
method: printer.gcode.script
icon: arrow-right
params: {"script": "CUT_FILAMENT"}

[menu __main 3ms cutter release]
name: Release Filament
method: printer.gcode.script
icon: arrow-left
params: {"script": "RELEASE_FILAMENT"}

[menu __main 3ms cutter routine]
name: Cut Routine
method: printer.gcode.script
icon: clock
params: {"script": "CUT_ROUTINE"}

[menu __print 3ms cutter]
name: Cutter
icon: filament

[menu __print 3ms cutter cut]
name: Cut Filament
method: printer.gcode.script
icon: arrow-right
params: {"script": "CUT_FILAMENT"}

[menu __print 3ms cutter release]
name: Release Filament
method: printer.gcode.script
icon: arrow-left
params: {"script": "RELEASE_FILAMENT"}

[menu __print 3ms cutter routine]
name: Cut Routine
method: printer.gcode.script
icon: clock
params: {"script": "CUT_ROUTINE"}
